site_name: api-reference

nav:
  - API Reference: "README.md"
  - Guides:
    - Quickstart: "guides/quickstart.md"
    - Authentication: "guides/authentication.md"
  - API: "api/README.md"
  - SDK: "sdk/nodejs.md"


  